### ISSUE TITLE
Contributing Error

### ISSUE THREAD

**Issue by JanRi3D** [tale/headplane#1]
[vite] Internal server error: Failed to load url ./magic (resolved id: ./magic) in /root/Headplane/app/routes/_data.dns._index/route.tsx. Does the file exist?
      at loadAndTransform (file:///root/Headplane/node_modules/.pnpm/vite@5.2.6/node_modules/vite/dist/node/chunks/dep-BBHrJRja.js:53848:21)
      at async instantiateModule (file:///root/Headplane/node_modules/.pnpm/vite@5.2.6/node_modules/vite/dist/node/chunks/dep-BBHrJRja.js:54902:10)

**Comment by JanRi3D** [comment]
When i run "npm run dev -- --host"
