### ISSUE TITLE
OIDC Login Error on Web UI - "Unexpected Server Error

### ISSUE THREAD

**Issue by 2TAP2B** [tale/headplane#37]
Problem

The OIDC setup configured in the config.yml works perfectly for adding new devices to Headscale, and API access functions without any issues. However, when attempting to log in to the web UI, I receive an "Unexpected Server Error."
Steps to Reproduce:

Set up OIDC in the config.yml as per documentation.
Successfully add a new device to Headscale using OIDC authentication.
    Try to log in to the Headscale web UI using the same OIDC setup.
    Encounter "Unexpected Server Error" on the web UI.

Expected Behavior:

I should be able to log into the web UI using OIDC without encountering any errors.
Actual Behavior:

The login attempt on the web UI results in an "Unexpected Server Error," although the OIDC setup works correctly for other functionalities (e.g., adding new devices and accessing via API).
Additional Information:

OIDC works for API access and device addition.
    This issue only occurs when trying to log in via the web UI.

Logs (If applicable):

If necessary, I can provide server logs that may help in troubleshooting the issue.

Any ideas on what might be causing the error, or how to troubleshoot further? Thanks in advance!

**Comment by tale** [comment]
I'll need logs to be able to determine anything at all. Also can you reproduce the issue with `DEBUG=true` set as an environment variable so that I can view all possible logs?

**Comment by 2TAP2B** [comment]
Hey,
i tried to narrow down the error a bit, but unfortunately i didn't get any further.
 i think it has something to do with the variable ‘ ROOT_API_KEY’ i'm not quite sure what to put in there. i tried it with a random string, the headscale api key, but nothing works.

Registering devices with OIDC works without problems, well... here are the logs

```
headplane  | 2024-10-12T19:13:20.112Z (INFO) [CTXT] Debug mode is enabled! Logs will spam a lot.
headplane  | 2024-10-12T19:13:20.119Z (INFO) [CTXT] Please disable debug mode in production.
headplane  | 2024-10-12T19:13:20.119Z (DEBG) [CTXT] Checking config at /etc/headscale/config.yml
headplane  | 2024-10-12T19:13:20.120Z (DEBG) [CFGX] Loading Headscale configuration from /etc/headscale/config.yml
headplane  | 2024-10-12T19:13:20.157Z (DEBG) [CFGX] Attempting to parse Headscale configuration
headplane  | 2024-10-12T19:13:20.165Z (DEBG) [CTXT] Checking write access to /etc/headscale/config.yml
headplane  | 2024-10-12T19:13:20.166Z (INFO) [INTG] Loading integration: docker
headplane  | 2024-10-12T19:13:20.166Z (DEBG) [INTG] Checking Docker integration availability
headplane  | 2024-10-12T19:13:20.166Z (INFO) [INTG] Using container: headscale
headplane  | 2024-10-12T19:13:20.167Z (INFO) [INTG] Checking socket: /var/run/docker.sock
headplane  | 2024-10-12T19:13:20.194Z (INFO) [INTG] Loaded integration: docker
headplane  | 2024-10-12T19:13:20.194Z (DEBG) [CTXT] Checking OIDC configuration
headplane  | 2024-10-12T19:13:20.195Z (DEBG) [CTXT] API Key Login Enabled: true
headplane  | 2024-10-12T19:13:20.195Z (DEBG) [CTXT] Checking ROOT_API_KEY and falling back to API_KEY
headplane  | 2024-10-12T19:13:20.195Z (DEBG) [CTXT] Checking OIDC environment variables
headplane  | 2024-10-12T19:13:20.196Z (DEBG) [CTXT] Issuer: undefined
headplane  | 2024-10-12T19:13:20.196Z (DEBG) [CTXT] Client: undefined
headplane  | 2024-10-12T19:13:20.196Z (INFO) [CTXT] Starting Headplane with Context
headplane  | 2024-10-12T19:13:20.197Z (INFO) [CTXT] HEADSCALE_URL: https://headscale.uk
headplane  | 2024-10-12T19:13:20.197Z (INFO) [CTXT] Integration: Docker
headplane  | 2024-10-12T19:13:20.198Z (INFO) [CTXT] Config: Found
headplane  | 2024-10-12T19:13:20.198Z (INFO) [CTXT] OIDC: Configured
headplane  | [remix-serve] http://localhost:3000 (http://0.0.0.0:3000)


headscale  | 2024-10-12T19:14:40Z ERR home/runner/work/headscale/headscale/hscontrol/app.go:375 > failed to validate token error="failed to parse ApiKey" client_address=172.18.0.2:52676
headplane  | 2024-10-12T19:14:40.536Z (DEBG) [APIC] POST https://headscale.uk/api/v1/apikey failed with status 500
headplane  | HeadscaleError: Unauthorized
headplane  |     at post (file:///app/build/server/index.js?t=1728630686000:88:11)
headplane  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
headplane  |     at finishOidc (file:///app/build/server/index.js?t=1728630686000:7018:23)
headplane  |     at Object.callRouteLoader (/app/node_modules/.pnpm/@remix-run+server-runtime@2.10.2_typescript@5.5.3/node_modules/@remix-run/server-runtime/dist/data.js:66:16)
headplane  |     at /app/node_modules/.pnpm/@remix-run+router@1.17.1/node_modules/@remix-run/router/router.ts:4817:21
headplane  |     at callLoaderOrAction (/app/node_modules/.pnpm/@remix-run+router@1.17.1/node_modules/@remix-run/router/router.ts:4879:16)
headplane  |     at async Promise.all (index 1)
headplane  |     at callDataStrategyImpl (/app/node_modules/.pnpm/@remix-run+router@1.17.1/node_modules/@remix-run/router/router.ts:4720:17)
headplane  |     at callDataStrategy (/app/node_modules/.pnpm/@remix-run+router@1.17.1/node_modules/@remix-run/router/router.ts:3975:19)
headplane  |     at loadRouteData (/app/node_modules/.pnpm/@remix-run+router@1.17.1/node_modules/@remix-run/router/router.ts:3919:19) {
headplane  |   status: 500
headplane  | }
headplane  | GET /admin/oidc/callback?code=910EMqfdCEXCnzAiwQBxPOQTjKWBC6Cp&state=BwP4aryxTYgP7oT9zhpUuVL9QUBfSFU5h0Vb4Gr_1As 500 - - 704.126 ms
```

**Comment by 2TAP2B** [comment]
So I'm also trying to setup different OIDC issuer and client directly in the docker compose.

```
headplane  | 2024-10-12T19:26:20.969Z (INFO) [CTXT] Debug mode is enabled! Logs will spam a lot.
headplane  | 2024-10-12T19:26:21.002Z (INFO) [CTXT] Please disable debug mode in production.
headplane  | 2024-10-12T19:26:21.002Z (DEBG) [CTXT] Checking config at /etc/headscale/config.yml
headplane  | 2024-10-12T19:26:21.003Z (DEBG) [CFGX] Loading Headscale configuration from /etc/headscale/config.yml
headplane  | 2024-10-12T19:26:21.043Z (DEBG) [CFGX] Attempting to parse Headscale configuration
headplane  | 2024-10-12T19:26:21.060Z (DEBG) [CTXT] Checking write access to /etc/headscale/config.yml
headplane  | 2024-10-12T19:26:21.099Z (INFO) [INTG] Loading integration: docker
headplane  | 2024-10-12T19:26:21.106Z (DEBG) [INTG] Checking Docker integration availability
headplane  | 2024-10-12T19:26:21.107Z (INFO) [INTG] Using container: headscale
headplane  | 2024-10-12T19:26:21.108Z (INFO) [INTG] Checking socket: /var/run/docker.sock
headplane  | 2024-10-12T19:26:21.110Z (INFO) [INTG] Loaded integration: docker
headplane  | 2024-10-12T19:26:21.118Z (DEBG) [CTXT] Checking OIDC configuration
headplane  | 2024-10-12T19:26:21.119Z (DEBG) [CTXT] API Key Login Enabled: true
headplane  | 2024-10-12T19:26:21.119Z (DEBG) [CTXT] Checking ROOT_API_KEY and falling back to API_KEY
headplane  | 2024-10-12T19:26:21.120Z (DEBG) [CTXT] Checking OIDC environment variables
headplane  | 2024-10-12T19:26:21.122Z (DEBG) [CTXT] Issuer: https://idp.headscale.uk
headplane  | 2024-10-12T19:26:21.126Z (DEBG) [CTXT] Client: 69588a4a-630f-4f95-b9f2-192274cfda8f
headplane  | 2024-10-12T19:26:21.127Z (INFO) [CTXT] Starting Headplane with Context
headplane  | 2024-10-12T19:26:21.127Z (INFO) [CTXT] HEADSCALE_URL: https://hs.headscale.uk
headplane  | 2024-10-12T19:26:21.127Z (INFO) [CTXT] Integration: Docker
headplane  | 2024-10-12T19:26:21.128Z (INFO) [CTXT] Config: Found
headplane  | 2024-10-12T19:26:21.128Z (INFO) [CTXT] OIDC: Configured
headplane  | [remix-serve] http://localhost:3000 (http://0.0.0.0:3000)
headplane  | GET /admin/ 302 - - 15.462 ms
headplane  | 2024-10-12T19:26:49.486Z (DEBG) [APIC] GET https://hs.headscale.uk/api/v1/apikey
headplane  | 2024-10-12T19:26:49.546Z (DEBG) [APIC] GET https://hs.headscale.uk/api/v1/node
headplane  | 2024-10-12T19:26:49.549Z (DEBG) [APIC] GET https://hs.headscale.uk/api/v1/routes
headplane  | 2024-10-12T19:26:49.551Z (DEBG) [APIC] GET https://hs.headscale.uk/api/v1/user
headplane  | GET /admin/machines 200 - - 733.673 ms
headplane  | POST /admin/logout?_data=routes%2Flogout 204 - - 5.138 ms
headplane  | GET /admin/login?returnTo=%2Fadmin%2Flogout&_data=routes%2Flogin 200 - - 2.557 ms
headplane  | POST /admin/login?returnTo=%2Fadmin%2Flogout&_data=routes%2Flogin 204 - - 210.473 ms
headplane  | 2024-10-12T19:26:55.916Z (DEBG) [APIC] POST https://hs.headscale.uk/api/v1/apikey
headscale  | 2024-10-12T19:26:55Z ERR home/runner/work/headscale/headscale/hscontrol/app.go:375 > failed to validate token error="failed to parse ApiKey" client_address=172.18.0.3:49176
headplane  | 2024-10-12T19:26:55.947Z (DEBG) [APIC] POST https://hs.headscale.uk/api/v1/apikey failed with status 500
headplane  | HeadscaleError: Unauthorized
headplane  |     at post (file:///app/build/server/index.js?t=1728630686000:88:11)
headplane  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
headplane  |     at finishOidc (file:///app/build/server/index.js?t=1728630686000:7018:23)
headplane  |     at Object.callRouteLoader (/app/node_modules/.pnpm/@remix-run+server-runtime@2.10.2_typescript@5.5.3/node_modules/@remix-run/server-runtime/dist/data.js:66:16)
headplane  |     at /app/node_modules/.pnpm/@remix-run+router@1.17.1/node_modules/@remix-run/router/router.ts:4817:21
headplane  |     at callLoaderOrAction (/app/node_modules/.pnpm/@remix-run+router@1.17.1/node_modules/@remix-run/router/router.ts:4879:16)
headplane  |     at async Promise.all (index 1)
headplane  |     at callDataStrategyImpl (/app/node_modules/.pnpm/@remix-run+router@1.17.1/node_modules/@remix-run/router/router.ts:4720:17)
headplane  |     at callDataStrategy (/app/node_modules/.pnpm/@remix-run+router@1.17.1/node_modules/@remix-run/router/router.ts:3975:19)
headplane  |     at loadRouteData (/app/node_modules/.pnpm/@remix-run+router@1.17.1/node_modules/@remix-run/router/router.ts:3919:19) {
headplane  |   status: 500
headplane  | }
headplane  | GET /admin/oidc/callback?code=sBjH81UIRkQZ9RoxehSCc64QdfRKOd2g&state=ogP7jVfsLcgrrrLrTpfH1vLwmOVVySbx9zEz9bqbbX4 500 - - 727.652 ms
```
The Browser only shows:
Unexpected Server Error

**Comment by tale** [comment]
Are you sure that your `ROOT_API_KEY` is a valid Headscale API key that isn't expired?

**Comment by 2TAP2B** [comment]
thanks for the tip, that was the problem. i used an expired api key...
now everything works
