### ISSUE TITLE
No UI?

### ISSUE THREAD

**Issue by gitwittidbit** [tale/headplane#61]
Hi,

so I just spun up the advanced integration stack with headscale and headplane, created an .env file and a configs/config.yaml file.

The containers start and show no errors but when I access ports 3000 (headplane) and 8080 (headscale) I just get a blank screen.

Cookie secure is set to false (as per the official example files).

What am I missing?

Thanks

**Comment by tale** [comment]
`/admin` route.

**Comment by gitwittidbit** [comment]
Thanks for the quick reply.

This actually got me one step further. But only one: 

Now I am seeing "Unexpected Server Error" on screen and in the docker logs I find:

`TypeError: fetch failed
    at node:internal/deps/undici/undici:13392:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async startOidc (file:///app/build/server/index.js:6947:20)
    at async callRouteLoader (file:///app/build/headplane/assets/index-ZVdnb7Ap.js:39932:16)
    at async file:///app/build/headplane/assets/index-ZVdnb7Ap.js:38325:19
    at async callLoaderOrAction (file:///app/build/headplane/assets/index-ZVdnb7Ap.js:38390:16)
    at async Promise.all (index 0)
    at async defaultDataStrategy (file:///app/build/headplane/assets/index-ZVdnb7Ap.js:38253:17)
    at async callDataStrategyImpl (file:///app/build/headplane/assets/index-ZVdnb7Ap.js:38284:17)
    at async callDataStrategy (file:///app/build/headplane/assets/index-ZVdnb7Ap.js:38095:19) {
  [cause]: Error: getaddrinfo ENOTFOUND sso.example.com
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'sso.example.com'
  }
`
This seems to suggest that the non-configuration of SSO is causing an issue. 

However, should it not work without OIDC? The config.yaml file has this setting: `only_start_if_oidc_is_available: false`
