### ISSUE TITLE
OIDC settings should be ignored if `only_start_if_oidc_is_available` is false.

### ISSUE THREAD

**Issue by tale** [tale/headplane#63]
"Unexpected Server Error" on screen and in the docker logs I find:

`TypeError: fetch failed
    at node:internal/deps/undici/undici:13392:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async startOidc (file:///app/build/server/index.js:6947:20)
    at async callRouteLoader (file:///app/build/headplane/assets/index-ZVdnb7Ap.js:39932:16)
    at async file:///app/build/headplane/assets/index-ZVdnb7Ap.js:38325:19
    at async callLoaderOrAction (file:///app/build/headplane/assets/index-ZVdnb7Ap.js:38390:16)
    at async Promise.all (index 0)
    at async defaultDataStrategy (file:///app/build/headplane/assets/index-ZVdnb7Ap.js:38253:17)
    at async callDataStrategyImpl (file:///app/build/headplane/assets/index-ZVdnb7Ap.js:38284:17)
    at async callDataStrategy (file:///app/build/headplane/assets/index-ZVdnb7Ap.js:38095:19) {
  [cause]: Error: getaddrinfo ENOTFOUND sso.example.com
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'sso.example.com'
  }
`
This seems to suggest that the non-configuration of SSO is causing an issue. 

However, should it not work without OIDC? The config.yaml file has this setting: `only_start_if_oidc_is_available: false`

_Originally posted by @gitwittidbit in https://github.com/tale/headplane/issues/61#issuecomment-2520344918_

**Comment by gitwittidbit** [comment]
Maybe the term "non-configuration" is misleading. While I did not configure it, given that there is this example config already present, "mis-configuration" is probably closer to the truth.

**Comment by tale** [comment]
Live in `0.3.9`!
