### ISSUE TITLE
DNS Page shows `Cannot read properties of undefined (reading 'map')`

### ISSUE THREAD

**Issue by arcoast** [tale/headplane#7]
Attempting to go to the DNS page throws an error message

```
Cannot read properties of undefined (reading 'map')
```
![image](https://github.com/tale/headplane/assets/81871508/775dc399-f96b-4e7c-b847-a20ffc822c27)

In the logs:
```
2024-05-05T19:47:52.908171962Z GET /admin/dns?_data=routes%2F_data.dns._index 200 - - 2.344 ms
2024-05-05T19:52:43.188919535Z TypeError: Cannot read properties of undefined (reading 'map')
2024-05-05T19:52:43.188950076Z     at Domains (file:///app/build/server/index.js?t=1714546338000:1970:30)
2024-05-05T19:52:43.188953207Z     at Uc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:70:44)
2024-05-05T19:52:43.188954830Z     at Xc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:72:253)
2024-05-05T19:52:43.188956575Z     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:78:89)
2024-05-05T19:52:43.188958039Z     at Yc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:81:98)
2024-05-05T19:52:43.188959496Z     at $c (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:80:140)
2024-05-05T19:52:43.188960916Z     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:78:345)
2024-05-05T19:52:43.188962319Z     at Yc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:81:98)
2024-05-05T19:52:43.188963810Z     at Xc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:73:145)
2024-05-05T19:52:43.188965283Z     at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:78:89)
2024-05-05T19:52:43.194205849Z GET /admin/dns 500 - - 86.168 ms
2024-05-05T19:52:43.394923776Z Error: No route matches URL "/favicon.ico"
2024-05-05T19:52:43.394944376Z     at getInternalRouterError (/app/node_modules/.pnpm/@remix-run+router@1.15.3/node_modules/@remix-run/router/router.ts:4519:5)
2024-05-05T19:52:43.394946959Z     at Object.query (/app/node_modules/.pnpm/@remix-run+router@1.15.3/node_modules/@remix-run/router/router.ts:2958:19)
2024-05-05T19:52:43.394948534Z     at handleDocumentRequestRR (/app/node_modules/.pnpm/@remix-run+server-runtime@2.8.1_typescript@5.4.3/node_modules/@remix-run/server-runtime/dist/server.js:184:35)
2024-05-05T19:52:43.394950208Z     at requestHandler (/app/node_modules/.pnpm/@remix-run+server-runtime@2.8.1_typescript@5.4.3/node_modules/@remix-run/server-runtime/dist/server.js:108:24)
2024-05-05T19:52:43.394951778Z     at /app/node_modules/.pnpm/@remix-run+express@2.8.1_express@4.19.2_typescript@5.4.3/node_modules/@remix-run/express/dist/server.js:41:28
2024-05-05T19:52:43.396383575Z GET /favicon.ico 404 - - 54.286 ms
```

Now I have been editing my headscale config, although everything seems to be fine and working, so I'm going to nuke and pave and see if I can reproduce this on a fresh install and will report back, as it's entirely possible I've found some weird edge case as it was working fine previously.

I've rolled back both headscale to alpha9 and headplane to `0.1.1` and `0.1.2` without any change

**Comment by tale** [comment]
Does your configuration have the search domains array and the nameservers array? I think right now I'm blindly accepting that those will always be defined even though they are completely optional and should fall back.

**Comment by tale** [comment]
Is this fixed on 0.1.5?

**Comment by arcoast** [comment]
Sorry @tale, been afk for a while, time has been in short supply.  I actually think you were right and it was to do with the nameservers, I nuked my config and couldn't reproduce and `0.1.5` is working well.

**Comment by Enissay** [comment]
> Error: No route matches URL "/favicon.ico"
@tale btw, favicon is still missing!

**Comment by tale** [comment]
Need a designer for the logo 🤕

**Comment by Enissay** [comment]
I am no designer but a I had a little discussion with chatgpt who suggested these:

 - Design 1:
![Image](https://github.com/user-attachments/assets/2b384f99-8b00-44c6-8cf7-2dab26beaf72)

 - Design 2:
![Image](https://github.com/user-attachments/assets/3378110c-66eb-4ef3-8e3a-a322f7d6175d)

 - Design 3:
![Image](https://github.com/user-attachments/assets/896945f2-f077-462d-a2d9-b9fdb9bdf6a5)
