### ISSUE TITLE
OIDC - token_endpoint_auth_method unsupported method 

### ISSUE THREAD

**Issue by moookino** [tale/headplane#70]
I checked https://github.com/tale/headplane/issues/57 changes as part of 0.3.7
but I'm still getting error, when trying to use OIDC to login

```

UnsupportedOperationError: unsupported client token_endpoint_auth_method

    at clientAuthentication (file:///app/node_modules/.pnpm/oauth4webapi@2.17.0/node_modules/oauth4webapi/build/index.js:455:19)

    at authenticatedRequest (file:///app/node_modules/.pnpm/oauth4webapi@2.17.0/node_modules/oauth4webapi/build/index.js:915:11)

    at tokenEndpointRequest (file:///app/node_modules/.pnpm/oauth4webapi@2.17.0/node_modules/oauth4webapi/build/index.js:933:12)

    at authorizationCodeGrantRequest (file:///app/node_modules/.pnpm/oauth4webapi@2.17.0/node_modules/oauth4webapi/build/index.js:1120:12)

    at finishOidc (file:///app/build/server/index.js:827:31)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async callRouteLoader (file:///app/build/headplane/assets/index-C13YWu_9.js:40447:16)

    at async file:///app/build/headplane/assets/index-C13YWu_9.js:38830:19

    at async callLoaderOrAction (file:///app/build/headplane/assets/index-C13YWu_9.js:38895:16)

    at async Promise.all (index 0)
```

and on authelia side I'm getting :
```
2024-12-16T19:27:33+01:00 DBG error=failed to parse content of Authorization header: invalid scheme: scheme with name 'token' is unknown method=GET msg=Error occurred while attempting to authenticate a request but the matched rule was a bypass rule path=/api/authz/forward-auth 
```

Can you help me to understand if I miss smth in the setup?

```services:
  headscale:
    image: headscale/headscale:0.23.0
    container_name: headscale
    restart: unless-stopped
    environment:
      - TZ=Europe/Prague
    volumes:
      - ./config:/etc/headscale
      - ./data:/var/lib/headscale
      - headscale-run:/var/run/headscale
    entrypoint: headscale serve
    networks:
      - proxy
    labels:
      traefik.enable: "true"
      traefik.docker.network: "proxy"
      # Configure service and router
      traefik.http.routers.headscale.entrypoints: http
      traefik.http.routers.headscale.rule: Host(`vpn.example.com`)
      traefik.http.routers.headscale.middlewares: headscale-cors
      traefik.http.routers.headscale-secure.entrypoints: https
      traefik.http.routers.headscale-secure.rule: Host(`vpn.example.com`)
      traefik.http.routers.headscale-secure.tls: true
      traefik.http.routers.headscale-secure.tls.certresolver: http
      traefik.http.routers.headscale-secure.service: headscale
      traefik.http.services.headscale.loadbalancer.server.port: 8080
       # Configure CORS middleware if needed
      traefik.http.middlewares.headscale-cors.headers.accesscontrolallowmethods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
      traefik.http.middlewares.headscale-cors.headers.accesscontrolallowheaders: "Authorization,*"
#     traefik.http.middlewares.headscale-cors.headers.accesscontrolallowheaders: "*"
      traefik.http.middlewares.headscale-cors.headers.accesscontrolalloworiginlist: ""  # Add other origins if needed
      traefik.http.middlewares.headscale-cors.headers.accesscontrolmaxage: 102
      traefik.http.middlewares.headscale-cors.headers.addvaryheader: true
       # UDP ports for DERP, etc
      traefik.udp.services.headscale-udp-41639.loadbalancer.server.port: 41641
      traefik.udp.services.headscale-udp-3476.loadbalancer.server.port: 3478
      com.centurylinklabs.watchtower.enable: true


  headplane:
    container_name: headplane
    image: ghcr.io/tale/headplane:latest
    restart: unless-stopped
    volumes:
      - './config:/etc/headscale'
      - './data:/var/lib/headscale'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    environment:
      DEBUG: 'true'
      HEADSCALE_URL: 'http://vpn.example.com'
      COOKIE_SECRET: 'abcdefghijklmnopqrstuvwxyz'
      HEADSCALE_CONTAINER: 'headscale'
      HEADSCALE_INTEGRATION: 'docker'
      CONFIG_FILE: '/etc/headscale/config.yaml'
      # These are all optional!
      ROOT_API_KEY: 'valid key' - tested with postman
      OIDC_CLIENT_ID: 'headplane'
      OIDC_ISSUER: 'https://sso.example.com'
      OIDC_CLIENT_SECRET: 'redacted'
      OIDC_CLIENT_SECRET_METHOD: 'post'
      DISABLE_API_KEY_LOGIN: 'true'
      COOKIE_SECURE: 'false'
      # These are the default values
      HOST: '0.0.0.0'
      PORT: '3000'
    networks:
    - proxy
    labels:
      traefik.enable: "true"
      traefik.docker.network: "proxy"
      traefik.http.services.headscale-admin.loadbalancer.server.port: 3000
      traefik.http.services.headscale-admin.loadbalancer.server.scheme: http
      traefik.http.routers.headscale-admin.rule: Host(`vpn.example.com`) && PathPrefix(`/admin`)
      traefik.http.routers.headscale-admin.entrypoints: https
      traefik.http.routers.headscale-admin.service: headscale-admin

      traefik.http.routers.headscale-admin.tls.certresolver: http
      traefik.http.routers.headscale-admin.middlewares: authelia@docker



volumes:

  headscale-run:

networks:
  proxy:
    external: true
```

```
      - client_id: 'headplane'
        client_name: 'Headplane'
        client_secret: 'redacted'
        public: false
        authorization_policy: 'one_factor'
        token_endpoint_auth_method: 'client_secret_post'
#       allow_multiple_auth_methods: true
        consent_mode: 'implicit'
        redirect_uris:
          - 'https://vpn.example.com/oidc/callback'
          - 'https://vpn.exmaple.com/admin/oidc/callback'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
        userinfo_signed_response_alg: 'none'
```

**Comment by tale** [comment]
Let me look into this  and I'll see what we can do.

**Comment by tale** [comment]
You need to set the `OIDC_CLIENT_SECRET_METHOD` to `client_secret_post`, not POST!

**Comment by moookino** [comment]
I was able to pass Authelia now without any errors, but now I'm getting
```
2024-12-19T09:57:02+01:00 ERR home/runner/work/headscale/headscale/hscontrol/app.go:357 > missing "Bearer " prefix in "Authorization" header client_address=172.18.0.2:45044
```
when I try to GET
```
curl --location 'http://vpn.murrum.eu/api/v1/node' \
--header 'Authorization: Bearer token'
```
I also checked closed issues related to the same problem, but it seems token wasn't valid and that was an issue
Token in my case was created after user was registered with OIDC, so it's tied to the same OIDC user
I used 
```docker exec headscale headscale apikeys create --expiration 999d```

Can you help me to understand what else could be missing?

**Comment by tale** [comment]
Are you running Headplane via a reverse proxy via HTTPS? It seems like CORS or something is preventing the browser or Headplane itself from sending headers to Headscale when trying to query it.
