### ISSUE TITLE
HeadscaleError: Unauthorized (when using OIDC)

### ISSUE THREAD

**Issue by yeahthegoys** [tale/headplane#73]
When logging into headplane interface via OIDC, I get the following error (bottom of post) in the headplane container logs. I have tried changing the headplane URL to the local URL instead of the public one, and disabling secure cookies, no combination of settings seem to work. It always fails the same way.

OIDC Login works perfectly fine when authenticating to the headscale server from a tailscale client on windows. I have had zero issues with this.

My oidc provider is an Authentik configuration with the standard, default scopes

I am using the full integration. Headplane is reading the OIDC information from Headscale's config.yaml, I also have the docker integration enabled not that it matters for these purposes.

I have also noticed that despite this statement in the docs stating that the OIDC variables are not required: 

> "If you want to use OpenID Connect for SSO, you'll need to provide these variables. Headplane will utilize the expiry of your tokens to determine the expiry of the session. If you use the Headscale configuration integration, these are not required."

Headplane will complain in the logs that the ROOT_API_KEY is missing if I don't include it so I have to add that in the compose file, but it reads everything else in just fine.

I am able to login to headplane by generating an API key via CLI but I would obviously prefer to use SSO.

Headplane and Headscale are both on the same subdomain and using Caddy. Caddy configuration below. Caddy is also responsible for the certificates which works fine.
```
scale.mydomain.com {
    reverse_proxy /admin* headplane:3000
    reverse_proxy headscale:8080
}
```

Maybe also worth mentioning my domain is behind Cloudflare's proxy servers. The Cloudflare proxy server IPs are configured as trusted proxies via the global config option. Something like:
```
{
	servers {
		trusted_proxies static private_ranges 173.245.48.0/20 103.21.244.0/22 103.22.200.0/22 103.31.4.0/22 141.101.64.0/18 108.162.192.0/18 190.93.240.0/20 188.114.96.0/20 197.234.240.0/22 198.41.128.0/17 162.158.0.0/15 104.16.0.0/13 104.24.0.0/14 172.64.0.0/13 131.0.72.0/22
		trusted_proxies_strict
	}
}
```

And finally the error that always shows up in the logs when authenticating to headplane:
```
HeadscaleError: Unauthorized
    at post (file:///app/build/server/index.js:94:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async finishOidc (file:///app/build/server/index.js:838:23)
    at async callRouteLoader (file:///app/build/headplane/assets/index-C13YWu_9.js:40447:16)
    at async file:///app/build/headplane/assets/index-C13YWu_9.js:38830:19
    at async callLoaderOrAction (file:///app/build/headplane/assets/index-C13YWu_9.js:38895:16)
    at async Promise.all (index 0)
    at async defaultDataStrategy (file:///app/build/headplane/assets/index-C13YWu_9.js:38758:17)
    at async callDataStrategyImpl (file:///app/build/headplane/assets/index-C13YWu_9.js:38789:17)
    at async callDataStrategy (file:///app/build/headplane/assets/index-C13YWu_9.js:38600:19) {
  status: 500
}
```

plz halp.

**Comment by yeahthegoys** [comment]
Never mind I'm such an idiot its so embarrassing I won't even say what it was.

**Comment by yeahthegoys** [comment]
> I have the same error and I'm going around in circles. Could you tell me what I missed configuring in your case? I have a similar configuration but with Azure OIDC

If you're having the same issue I was having, its that OIDC is only authenticating to Headplane, not the underlying headscale instance. Therefore to give your OIDC users access to headscale, Headplane needs an API key to authenticate to Headscale, in order to create permissions and modify things in such a way that the OIDC users also have access. This is just from memory, I dont have my instance running at the moment and I haven't looked at it in a while.

So you need to set Headplane's ROOT_API_KEY env var to an API key, generated in Headscale, using:
`headscale apikeys create --expiration 999d`
